version: '3.9'

services:
    schema:
        image: flyway/flyway
        container_name: fable-db-flyway
        command: -url=${DB_CONN_URL_DOCKER} -schemas=migration -user=${DB_USER} -password=${DB_PWD} -connectRetries=60 migrate
        volumes:
            - ./schema:/flyway/sql
        profiles:
            - na

    db:
        image: mysql/mysql-server
        container_name: fable-db
        command: [ "--default-authentication-plugin=mysql_native_password" ]
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PWD}
            - MYSQL_ROOT_HOST=%
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"
        profiles:
            - dev
volumes:
    mysql-data:
