### health
# @name=health
GET {{api-host}}/health

### create org
# @name=new_org
POST {{api-host}}/v1/neworg
Content-Type: application/json

{
  "displayName": "Acme"
}

### get org
# @name=get_org
GET {{api-host}}/v1/org?id=2
Accept: application/json

### create user
POST {{api-host}}/v1/newuser
Content-Type: application/json

{
  "firstName": "root",
  "lastName": "root",
  "email": "root@root.com",
  "belongsToOrg": 2
}
