### Index creation. Directly create in elastic search
PUT {{host}}/asset-content
content-type: application/json

< ../src/main/resources/es.index.schema.json

### Delete data from index. ONLY FOR LOCAL INSTANCE.
DELETE http://localhost:9200/asset-content

### Delete a doc
DELETE http://localhost:9200/asset-content/_doc/VEm2vIMBbHh_dWAYXUx-

### Delete by query
POST http://localhost:9200/asset-content/_delete_by_query

{
  "query": {
    "match": {
      "assetId": -1
    }
  }
}

### query index that was already created
GET {{host}}/asset-content?pretty

