package com.sharefable.api.transport;

@GenerateTSDef
public enum JobType {
    TRANSCODE_VIDEO,
    RESIZE_IMG,
    DELETE_ASSET,
    REFRESH_CRAWLER,
    REFRESH_CRAWLER_FOR_ANN_USER_ASSIGN,
    REFRESH_TOUR_ANN_CLICK,
    REFRESH_TOUR_CONVERSION,
    REFRESH_TOUR_METRICS,
    REFRESH_USER_AID_MAPPING,
    REFRESH_AID_SID_MAPPING,
    REFRESH_LEAD_ACTIVITY,
    ROLLUP_METRICS_CURRENT_TO_DAILY,
    ROLLUP_CONVERSION_CURRENT_TO_DAILY,
    ROLLUP_ANN_CLICK_CURRENT_TO_DAILY
}
