com.sharefable.api.s3.root-qualifier=root
com.sharefable.api.q.region=ap-southeast-1
com.sharefable.api.s3.cdn=
#sentry
sentry.dsn=https://SENTRY_DSN_1.ingest.sentry.io/SENTRY_DSN_2
sentry.traces-sample-rate=1.0
sentry.exception-resolver-order=-2147483647
sentry.environment=${APP_ENV}
