# Spring jdbc config
spring.datasource.url=${DB_HOST}/fable_app
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PWD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect.storage_engine=innodb
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.use-new-id-generator-mappings=true
spring.jpa.properties.hibernate.event.merge.entity_copy_observer=allow

logging.level.root=WARN
logging.level.com.sharefable.api=INFO

server.port=8080

# api config
com.sharefable.api.s3.proxy-asset-bucket-name=${ASSET_BUCKET_NAME}
com.sharefable.api.s3.access-key-id=${AWS_ACCESS_KEY_ID}
com.sharefable.api.s3.access-key-secret=${AWS_SECRET_ACCESS_KEY}
com.sharefable.api.s3.region=${AWS_S3_REGION}

# TODO[dev] Only during development
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.type=trace

