com.sharefable.api.s3.root-qualifier=root
com.sharefable.api.q.region=${SQS_QUEUE_REGION:us-east-1}
com.sharefable.api.s3.cdn=${ASSET_CDN}
com.sharefable.app.dns=${APP_URL:https://demo.zrexsolutions.com}
com.sharefable.api.self.public-endpoint=${API_PUBLIC_ENDPOINT:https://api.demo.zrexsolutions.com}
#sentry
sentry.dsn=${SENTRY_DSN}
sentry.traces-sample-rate=1.0
sentry.exception-resolver-order=-2147483647
sentry.environment=${APP_ENV}
sentry.send-default-pii=true
sentry.max-request-body-size=ALWAYS
sentry.release=@pom.version@
auth0.audiences=${AUTH0_AUDIENCE:https://api.demo.zrexsolutions.com}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI:https://zrexsolutions-demo.us.auth0.com/}
com.sharefable.payment.ai-charge-id=ai-credit-USD
