# Spring jdbc config
spring.datasource.url=${DB_HOST}/fable_app
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PWD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.use-new-id-generator-mappings=true
spring.jpa.properties.hibernate.event.merge.entity_copy_observer=allow

logging.level.root=WARN
logging.level.com.sharefable.appserver=INFO

server.port=8080
