name: DB Migration & Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        type: environment
        description: Deployment environment?
        required: true
      migration:
        type: boolean
        description: Run DB migration?
        default: false
        required: true
      deploy_to_ecs:
        type: boolean
        description: Deploy to ECS?
        default: false
        required: true

#env:
#  #  DEPLOY_ENV: ${{ github.ref_name == 'master' && 'prod' ||  github.ref_name == 'develop' && 'staging' || 'na' }}
#  DEPLOY_ENV: prod

jobs:
  db-migration:
    if: github.event.inputs.migration == 'true' && contains('["agfabl"]', github.actor)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write

    steps:
      - run: echo "Running db migration in ${{ github.event.inputs.deploy_env }}"

      - run: echo "Triggered by ${{ github.actor }}"

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Creating empty env file
        run: touch env.now

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          role-session-name: app-deployment

      - name: Feed env from parameter store
        run: >
          echo "export DB_USER=$(aws ssm get-parameter --region ${{ vars.DEFAULT_REGION }} --name "${{ env.DEPLOY_ENV }}.api.DB_USER" --query 'Parameter.Value' --output text)" >> env.now &&
          echo "export DB_PWD=$(aws ssm get-parameter --region ${{ vars.DEFAULT_REGION }} --name "${{ env.DEPLOY_ENV }}.api.DB_PWD" --query 'Parameter.Value' --output text)" >> env.now &&
          echo "export DB_CONN_URL_DOCKER=$(aws ssm get-parameter --region ${{ vars.DEFAULT_REGION }} --name "${{ env.DEPLOY_ENV }}.api.DB_CONN_URL" --query 'Parameter.Value' --output text)" >> env.now

      - name: show file content
        run: >
          cat env.now

  deploy-to-ecs:
    if: ! success() && ! cancelled() && github.event.inputs.deploy_to_ecs == 'true' && contains('["agfabl"]', github.actor)
    runs-on: ubuntu-latest
    needs: db-migration
    permissions:
      id-token: write
      contents: read
      issues: write

    steps:
      - run: echo "Deploying to ECS in ${{ github.event.inputs.deploy_env }}"
