name: Build and Deploy api container

on:
  push:
    branches: [ env-based-cicd ]

env:
  #  DEPLOY_ENV: ${{ github.ref_name == 'master' && 'prod' ||  github.ref_name == 'develop' && 'staging' || 'na' }}
  DEPLOY_ENV: prod

jobs:
  build-and-install:
    runs-on: ubuntu-latest
    #    environment: ${{ github.ref_name == 'master' && 'prod' ||  github.ref_name == 'develop' && 'staging' || 'na' }}
    environment: prod
    permissions:
      id-token: write
      contents: read
      issues: write

    steps:
      - name: Deploy env [TODO] replace it with manual approval
        run: echo "${{ env.DEPLOY_ENV }}"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup jq
        uses: dcarbone/install-jq-action@v1.0.1

      - name: 'Check jq'
        run: |
          which jq
          jq --version         

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Getting project version
        id: version
        run: |
          echo "V=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Printing version
        run: |
          echo "Building for version ${{ steps.version.outputs.V }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          role-session-name: app-deployment


      - name: Checking if tag is present in ecr
        run: >
          if aws ecr describe-images --repository-name fable-api --region ap-southeast-1 --query 'sort_by(imageDetails,& imagePushedAt)[*].imageTags[]' | grep -q ${{ steps.version.outputs.V }}; then
            echo "::error::Image ${{ steps.version.outputs.V }} already present in registry. Update version in pom.xml"; exit 1
          else
            echo "Image not found in registry. Will create a new tag with ${{ steps.version.outputs.V }}"
          fi

      - name: Creating empty env file
        run: touch env.now

#  db-migration:
#    if: github.event.inputs.migration == 'yes'
#    needs: build-and-install
#    runs-on: ubuntu-latest
#    environment: prod
#    permissions:
#      id-token: write
#      contents: read
#      issues: write
#
#    steps:
#      - name: Migrating to [TODO] replace it with manual approval
#        run: echo "${{ env.DEPLOY_ENV }}"
#
#      - name: Checkout Repository
#        uses: actions/checkout@v3
#
#      - name: Creating empty env file
#        run: touch env.now
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-region: us-east-1
#          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
#          role-session-name: app-deployment
#
#      - name: Feed env from parameter store
#        run: >
#          echo "export DB_USER=$(aws ssm get-parameter --region ${{ vars.DEFAULT_REGION }} --name "${{ env.DEPLOY_ENV }}.api.DB_USER" --query 'Parameter.Value' --output text)" >> env.now &&
#          echo "export DB_PWD=$(aws ssm get-parameter --region ${{ vars.DEFAULT_REGION }} --name "${{ env.DEPLOY_ENV }}.api.DB_PWD" --query 'Parameter.Value' --output text)" >> env.now &&
#          echo "export DB_CONN_URL_DOCKER=$(aws ssm get-parameter --region ${{ vars.DEFAULT_REGION }} --name "${{ env.DEPLOY_ENV }}.api.DB_CONN_URL" --query 'Parameter.Value' --output text)" >> env.now
#
#      - name: show file content
#        run: >
#          cat env.now
